# Generated by Django 4.1.1 on 2023-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('physics', models.IntegerField(max_length=100)),
                ('chemistry', models.IntegerField(max_length=100)),
                ('maths', models.IntegerField(max_length=100)),
                ('computer_science', models.IntegerField(max_length=100)),
            ],
        ),
    ]
