# Generated by Django 4.1.1 on 2023-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='chemistry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='computer_science',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='physics',
            field=models.IntegerField(),
        ),
    ]
